name: villa3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cyrus-sasl=2.1.28=h1110e0f_2
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.14.1=h31d0fb7_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_1
  - libprotobuf=5.29.3=h3cdef7c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - mesalib=25.1.5=h31e3550_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - pyqt=6.7.1=py312h8dad735_2
  - pyqt6-sip=13.9.1=py312h6ce4db3_2
  - python=3.12.11=h22baa00_0
  - qtbase=6.7.3=h10a5587_3
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py312h06a4308_0
  - sip=6.10.0=py312h6a678d5_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.31=h516909a_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - addict==2.4.0
      - aiobotocore==2.23.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - altgraph==0.17.4
      - annotated-types==0.7.0
      - app-model==0.4.0
      - appdirs==1.4.4
      - argparse==1.4.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - babel==2.17.0
      - blinker==1.9.0
      - blosc2==3.6.1
      - bokeh==3.7.3
      - botocore==1.39.8
      - build==1.2.2.post1
      - cachey==0.2.1
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - comm==0.2.3
      - configargparse==1.7.1
      - connected-components-3d==3.24.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.1.1
      - dask==2025.7.0
      - dask-image==2024.5.3
      - debugpy==1.8.15
      - decorator==5.2.1
      - deprecated==1.2.18
      - dicom2nifti==2.6.2
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - edt==3.0.0
      - einops==0.8.1
      - executing==2.2.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.1.1
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.59.0
      - freetype-py==2.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphviz==0.21
      - heapdict==1.0.1
      - hf-xet==1.1.5
      - hsluv==5.0.4
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - in-n-out==0.2.1
      - ipykernel==6.30.0
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libigl==2.6.1
      - lightning-utilities==0.15.0
      - linecache2==1.0.0
      - llvmlite==0.44.0
      - locket==1.0.0
      - lxml==6.0.0
      - macro-kit==0.4.9
      - magic-class==0.7.17
      - magicgui==0.10.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - napari==0.6.2
      - napari-console==0.1.3
      - napari-plugin-engine==0.2.0
      - napari-svg==0.2.1
      - narwhals==1.48.1
      - nbformat==5.10.4
      - ndindex==1.10.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nibabel==5.3.2
      - npe2==0.7.9
      - numba==0.61.2
      - numcodecs==0.15.1
      - numexpr==2.11.0
      - numpy==2.2.6
      - numpydoc==1.9.0
      - opencv-python-headless==4.12.0.88
      - pandas==2.3.1
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==11.3.0
      - pims==0.7
      - pint==0.24.4
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pooch==1.8.2
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - psygnal==0.14.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyconify==0.2.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-compat==0.1.2
      - pydantic-core==2.33.2
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.8
      - pynrrd==1.1.3
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-gdcm==3.0.26
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - rdkit==2025.3.3
      - referencing==0.36.2
      - requests==2.32.4
      - retrying==1.4.1
      - rich==14.1.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.26.0
      - s3fs==2025.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - sentry-sdk==2.33.2
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - six==1.17.0
      - slicerator==1.1.0
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soundfile==0.13.1
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - superqt==0.7.5
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - tomli-w==1.2.0
      - toolz==1.0.0
      - tornado==6.5.1
      - tqdm==4.67.1
      - traceback2==1.4.0
      - traitlets==5.14.3
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unittest2==1.1.0
      - urllib3==2.5.0
      - vesuvius==0.1.10
      - vispy==0.15.2
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xyzservices==2025.4.0
      - yacs==0.1.8
      - yarl==1.20.1
      - zarr==2.18.7
      - zipp==3.23.0
prefix: /home/seanpc/miniconda3/envs/villa2
