name: Continuous Integration (CI)

on:
  pull_request:
    paths:
      - 'volume-cartographer/**'
      - '.github/workflows/vc3d-ci.yml'

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./volume-cartographer

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: "{{defaultContext}}:volume-cartographer"
            file: ubuntu-24.04-noble.Dockerfile
            push: false
            tags: ${{ github.repository_owner }}/volume-cartographer:latest
